7. Neste exercício você irá comparar as classificações Multinomial e Bernoulli. Utilize as mensagens abaixo e seus respectivos rótulos para treinar um classificador naive Bayes
com distribuição de Bernoulli e outro classificador naive Bayes com distribuição Multinomial.
x_train = np.array(['Chinese Beijing Chinese',
'Chinese Chinese Shanghai',
'Chinese Macao',
'Tokyo Japan Chinese'])
y_train = np.array(['china','china','china','not china'])
Instancie um objeto da classe CountVectorizer com o parâmetro binary = True para o classificador naive Bayes com distribuição de Bernoulli. Para o classificador naive Bayes com distribuição Multinomial, instancie um objeto da classe CountVectorizer com o parâmetro binary = False . Em seguida, treine os classificadores. Utilize os seguintes comandos para verificar os nomes dos atributos e a matriz com a contagem dos atributos para cada instância da classe CountVectorizer , onde vect é o objeto da classe CountVectorizer e x_train_dtm é o matriz de contagem gerada pela execução do método fit_transform da classe CountVectorizer . Não se esqueça de transformar a mensagem de validação, x_test , com o método transform , antes de predizer sua classe para cada classificador.
print(vect.get_feature_names())
print(x_train_dtm.toarray())
De posse dos modelos treinados, pede-se
A. Imprima na tela de seu Notebook do Jupyter o nome dos atributos e a matriz de contagem dos atributos para cada uma das instâncias de CountVectorizer .
B. Utilize o método predict das classes BernoulliNB e MultinomialNB e preveja a qual classe a mensagem abaixo pertence para cada um dos classificadores. x_test = np.array(['Chinese Chinese Chinese Tokyo Japan'])
C. Calcule manualmente a probabilidade de cada classe, ou seja, ‘china’ e ‘not china’, dado a mensagem de teste para os 2 classificadores. Apresente os cálculos das probabilidades a priori e a posteriori .
D. Como você deve ter percebido, existe diferença na classificação feita pelos 2 classificadores. Explique o motivo da classificação feita por cada classificador.
( Dica : Imprima o vetor de contagens de cada classificador com o comando,
print(x_test_dtm.toarray())
compare as contagens de cada palavra no vetor, além disso, o (C) acima vai te ajudar a entender e responder este item).
OBSERVAÇÃO : quando você forem calcular as probabilidades condicionais, vocês irão se deparar com probabilidades nulas, e.g., P(‘japan’ | ‘china’) = 0, e isso faria com que as respostas finais fossem zeradas. Uma solução para esse problema é utilizar a suavização de Laplace também conhecida como suavização adicione 1 . Com a suavização as probabilidades condicionais se tornam P(xk | Cq) = , contagem(xk,Cq) + 1 contagem(x , C ) + V ΣK k=1 c k q | | onde contagem(xk,Cq) é número de vezes que a palavra xk aparece entre todas as palavras que pertencem à classe , é a soma total de palavras Cq ontagem(x , C ) ΣK k=1 c k q pertencentes à classe Cq e |V | é o tamanho do vocabulário, ou seja, o número de atributos. Por exemplo, para o Classificador BernoulliNB P(‘japan’ | ‘china’) = (0 + 1) / (6 + 6), onde =0, = 6 e = 6, pois ontagem(x japan , china ) c k = ′ ′ Cq = ′ ′ ontagem(x , C ) Σ K k=1 c k q |V | os atributos são 'beijing', 'chinese', 'japan', 'macao', 'shanghai' e 'tokyo'.

In [2]:
# Import all necessary libraries.
import pandas as pd
import numpy as np
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, roc_curve, auc
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
x_train = np.array(['Chinese Beijing Chinese',
                   'Chinese Chinese Shanghai',
                   'Chinese Macao',
                   'Tokyo Japan Chinese'])

y_train = np.array(['china','china','china','not china'])

x_test = np.array(['Chinese Chinese Chinese Tokyo Japan'])

In [4]:
#bernoulli

vect = CountVectorizer(binary=True)

x_train_dtm = vect.fit_transform(x_train)

print(vect.get_feature_names())
print()
print(x_train_dtm.toarray())
print()

x_test_dtm = vect.transform(x_test)

print(x_test_dtm.toarray())
print()

model = BernoulliNB(binarize=None)

model.fit(x_train_dtm, y_train)

y_pred_class = model.predict(x_test_dtm)

print(y_pred_class)
print()

print(model.predict_proba(x_test_dtm))

['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']

[[1 1 0 0 0 0]
 [0 1 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]]

[[0 1 1 0 0 1]]

['not china']

[[0.19106679 0.80893321]]


In [5]:
#multinomial
x_train = np.array(['Chinese Beijing Chinese',
                   'Chinese Chinese Shanghai',
                   'Chinese Macao',
                   'Tokyo Japan Chinese'])

y_train = np.array(['china','china','china','not china'])

x_test = np.array(['Chinese Chinese Chinese Tokyo Japan'])

vect = CountVectorizer()

x_train_dtm = vect.fit_transform(x_train)

print(vect.get_feature_names())
print()
print(x_train_dtm.toarray())
print()

x_test_dtm = vect.transform(x_test)

print(x_test_dtm.toarray())
print()

model = MultinomialNB()

model.fit(x_train_dtm, y_train)

y_pred_class = model.predict(x_test_dtm)

print(y_pred_class)
print()

print(model.predict_proba(x_test_dtm))

['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']

[[1 2 0 0 0 0]
 [0 2 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]]

[[0 3 1 0 0 1]]

['china']

[[0.68975861 0.31024139]]


R: Na classificação de bernoulli o vetor utilizado para testes é igual ao quarto vetor para treinamento, ficando classificado como 'not-china'.
Na classificação do multinomial é apresentado muitas vezes o indicador 'chinese'.